name: deployment service

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: Deploy to Production
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
