name: deployment service

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: Deploy to Production
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check branch
        id: branch-check
        run: echo "Branch is ${{ github.event.pull_request.base.ref }}"

      - name: Run your action
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: |
          echo "Running your action..."
          # Add your desired action or command here

      - name: Set up Node.js
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: npm install

      - name: Build React app
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: npm run build

      - name: Start server
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: |
          echo "Starting server..."
          nohup npx serve -s build -p 3000 > /dev/null 2>&1 &

          # Wait for the server to start (adjust the sleep time if needed)
          sleep 5

          # Check if the server is running
          if pgrep -f "npx serve -s build -p 3000" >/dev/null; then
            echo "Server running"
          else
            echo "Failed to start server"
            exit 1
          fi

      # Continue with other steps...
