name: deployment service

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: Deploy to Production
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check branch
        id: branch-check
        run: echo "Branch is ${{ github.event.pull_request.base.ref }}"

      - name: Run your action
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: |
          echo "Running your action..."
          # Add your desired action or command here

      - name: Set up Node.js
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: npm install

      - name: Build React app
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: npm run build

      - name: Start server
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: pm2 start npm --name "testing-integration" -- run server

      - name: Deploy to remote server
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: |
          # Variables
          remote_host="172.16.1.101"
          remote_directory="/projects/testin_ui"
          local_directory="/projects/deploy_builder/testin-cicd-with-github-actions/testin-cicd-with-github-actions"
          private_key="/home/a.malaika/.ssh/deployment_test"

          # Check if the PM2 process exists and stop it if it does
          ssh -i "$private_key" "$remote_host" "cd $remote_directory && pm2 start npm --name 'testing-integration' -- run server" 2>&1

          # Copy the entire folder to the remote server
          rsync -avz -e "ssh -i $private_key" "$local_directory/" "$remote_host:$remote_directory"
          
          # SSH into the remote server and run the pm2 command
          ssh -i "$private_key" "$remote_host" "cd $remote_directory && pm2 start npm --name 'testing-integration' -- run server"