name: Pull Request Closed

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check branch
        id: branch-check
        run: echo "Branch is ${{ github.event.pull_request.base.ref }}"

      - name: Run your action
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: |
          # Add your desired action commands here
          # For example, you can run tests, build artifacts, or deploy code



