name: Create Pull Request to Production

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
        git config user.name "Aime Malaika"
        git config user.email "aimemalaika1995@gmail.com"
      
    - name: Create branch
      run: |
        git checkout -b pr-branch
        git push origin pr-branch
      
    - name: Install hub
      run: |
        sudo apt-get install -y hub
      
    - name: Create Pull Request
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        hub pull-request -b production -h pr-branch -m "Automatically create pull request to production"
